metadata.format.version = "1.1"

[versions]

# Compile only
velocity = "3.2.0-SNAPSHOT"
libby = "1.2.0"
configurate = "4.1.2"
miniplaceholders = "1.3.1"

# Plugins
blossom = "1.3.1"
shadow = "8.1.1"
runvelocity = "2.0.1"

# Required by Configurate 4
geantyref = "1.3.13"

[libraries]

# Compile Only Dependencies
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
configurate = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }

# Included Dependencies
libby = { group = "net.byteflux", name = "libby-velocity", version.ref = "libby" }

miniplaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version = "2.0.0" }

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runvelocity" }